name: Dynamic Build Steps
description: Build SpeedReader with dynamic linking
runs:
  using: composite
  steps:
    - name: Install uv
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Install zig
      uses: mlugg/setup-zig@v2
    - name: Install Dotnet
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'
    - name: Build Dynamically Linked Binary
      shell: bash
      run: dotnet publish -r linux-x64 src/Frontend -p:OnnxLinkMode=Dynamic -p:BuildOnnx=true -p:BuildSROrt=true
    - name: Smoke Test
      shell: bash
      run: |
        src/Frontend/bin/Release/net10.0/linux-x64/publish/speedreader hello.png | grep '"text": "Hello"' || exit 1
    - name: Upload libonnxruntime.so
      uses: actions/upload-artifact@v4
      with:
        name: libonnxruntime.so
        path: src/Native/onnx/out/shared/libonnxruntime.so
    - name: Upload Dynamically Linked Binary
      uses: actions/upload-artifact@v4
      with:
        name: speedreader-dynamic
        path: src/Frontend/bin/Release/net10.0/linux-x64/publish/speedreader
    - name: Debug Info
      if: ${{ env.ACT && always() }}
      shell: bash
      run: uv run ./ci/get-container-id.py
