name: speedreader-dev
services:
  app:
    image: ${SPEEDREADER_IMAGE}
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5001
    volumes:
      - ./demo.html:/srv/demo.html:ro
    deploy:
      resources:
        limits:
          cpus: "6.0"
          memory: 8G

  caddy:
    image: caddy:2
    ports:
      - "${CADDY_PORT}:${CADDY_PORT}"
    environment:
      - CADDY_HOST
      - CADDY_PORT
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./demo.html:/srv/demo.html:ro

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    restart: unless-stopped
