name: speedreader-dev
services:
  app:
    image: ${SPEEDREADER_IMAGE}
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5000
    volumes:
      - ./demo.html:/srv/demo.html:ro
      - ./performance.html:/srv/performance.html:ro
    deploy:
      resources:
        limits:
          cpus: "6.0"
          memory: 8G
    networks:
      - monitoring

  caddy:
    image: caddy:2
    ports:
      - "8000:8000"
    environment:
      - CADDY_HOST
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./demo.html:/srv/demo.html:ro
      - ./performance.html:/srv/performance.html:ro
    networks:
      - monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    command:
      - '--v=0'
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    restart: unless-stopped
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--log.level=error'
    ports:
      - "9090:9090"
    volumes:
      - ./Monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
    volumes:
      - ./Monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./Monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_LOG_LEVEL=error
    networks:
      - monitoring

networks:
  monitoring:
