global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'speedreader'
    static_configs:
      - targets: ['192.168.0.12:5002']
    metrics_path: '/metrics'
    
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['192.168.0.12:8081']
    metrics_path: '/metrics'
