global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'speedreader'
    static_configs:
      - targets: ['app:5001']
    metrics_path: '/metrics'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: '/metrics'
