{
 "title": "Inference",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "model", "label": "Model", "query": "DbNet18,SVTRv2" }
  ]
 },
 "panels": [
  {
   "title": "Inference Duration (Percentiles)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n      time_bucket('5s', time) AS time,\n      metric_name AS metric,\n      percentile_cont(0.5) WITHIN GROUP (ORDER BY value) AS \"P50\",\n      percentile_cont(0.9) WITHIN GROUP (ORDER BY value) AS \"P90\",\n      percentile_cont(0.9999) WITHIN GROUP (ORDER BY value) AS \"P99.99\"\n  FROM metrics\n  WHERE $__timeFilter(time) \n    AND metric_name = 'speedreader.inference.duration'\n    AND tags->>'model' = '$model'\n  GROUP BY time_bucket('5s', time), metric_name\n  ORDER BY time;"
    }
   ]
  },
  {
   "title": "Throughput (inferences / sec)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n      time_bucket('5s', time) AS time,\n      metric_name AS metric,\n      SUM(value)/5 AS \"Throughput\"\n  FROM metrics\n  WHERE $__timeFilter(time)\n      AND metric_name = 'speedreader.inference.counter'\n      AND tags->>'model' = '$model'\n      AND time_bucket('5s', time) < time_bucket('5s', NOW())\n      AND time_bucket('5s', time) > time_bucket('5s', $__timeFrom()::timestamptz)\n  GROUP BY time_bucket('5s', time), metric_name\n  ORDER BY time;"
    }
   ]
  },
  {
   "title": "Parallelism",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n      time_bucket('5s', time) AS time,\n      metric_name AS metric,\n      AVG(value) AS \"Parallelism\"\n  FROM metrics\n  WHERE $__timeFilter(time) \n    AND metric_name = 'speedreader.inference.parallelism'\n    AND tags->>'model' = '$model'\n  GROUP BY time_bucket('5s', time), metric_name\n  ORDER BY time;"
    },
    {
     "rawSql": "SELECT\n      time_bucket('5s', time) AS time,\n      metric_name AS metric,\n      AVG(value) AS \"Max Parallelism\"\n  FROM metrics\n  WHERE $__timeFilter(time) \n    AND metric_name = 'speedreader.inference.max_parallelism'\n    AND tags->>'model' = '$model'\n  GROUP BY time_bucket('5s', time), metric_name\n  ORDER BY time;"
    }
   ]
  },
  {
   "title": "Inference Duration (HeatMap)",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "increase(InferenceDuration_milliseconds_bucket[1m])",
     "legendFormat": "__auto",
     "rawSql": "SELECT \n    time_bucket('5s', time) AS time,\n    SUM(CASE WHEN value >= 0 AND value < 25 THEN 1 ELSE 0 END) AS \"0\",\n    SUM(CASE WHEN value >= 25 AND value < 50 THEN 1 ELSE 0 END) AS \"25\",\n    SUM(CASE WHEN value >= 50 AND value < 75 THEN 1 ELSE 0 END) AS \"50\",\n    SUM(CASE WHEN value >= 75 AND value < 100 THEN 1 ELSE 0 END) AS \"75\",\n    SUM(CASE WHEN value >= 100 AND value < 125 THEN 1 ELSE 0 END) AS \"100\",\n    SUM(CASE WHEN value >= 125 AND value < 150 THEN 1 ELSE 0 END) AS \"125\",\n    SUM(CASE WHEN value >= 150 AND value < 175 THEN 1 ELSE 0 END) AS \"150\",\n    SUM(CASE WHEN value >= 175 AND value < 200 THEN 1 ELSE 0 END) AS \"175\",\n    SUM(CASE WHEN value >= 200 AND value < 225 THEN 1 ELSE 0 END) AS \"200\",\n    SUM(CASE WHEN value >= 225 AND value < 250 THEN 1 ELSE 0 END) AS \"225\",\n    SUM(CASE WHEN value >= 250 AND value < 275 THEN 1 ELSE 0 END) AS \"250\",\n    SUM(CASE WHEN value >= 275 AND value < 300 THEN 1 ELSE 0 END) AS \"275\",\n    SUM(CASE WHEN value >= 300 AND value < 325 THEN 1 ELSE 0 END) AS \"300\",\n    SUM(CASE WHEN value >= 325 AND value < 350 THEN 1 ELSE 0 END) AS \"325\",\n    SUM(CASE WHEN value >= 350 AND value < 375 THEN 1 ELSE 0 END) AS \"350\",\n    SUM(CASE WHEN value >= 375 AND value < 400 THEN 1 ELSE 0 END) AS \"375\",\n    SUM(CASE WHEN value >= 400 AND value < 425 THEN 1 ELSE 0 END) AS \"400\",\n    SUM(CASE WHEN value >= 425 AND value < 450 THEN 1 ELSE 0 END) AS \"425\",\n    SUM(CASE WHEN value >= 450 AND value < 475 THEN 1 ELSE 0 END) AS \"450\",\n    SUM(CASE WHEN value >= 475 AND value < 500 THEN 1 ELSE 0 END) AS \"475\",\n    SUM(CASE WHEN value >= 500 AND value < 525 THEN 1 ELSE 0 END) AS \"500\",\n    SUM(CASE WHEN value >= 525 AND value < 550 THEN 1 ELSE 0 END) AS \"525\",\n    SUM(CASE WHEN value >= 550 AND value < 575 THEN 1 ELSE 0 END) AS \"550\",\n    SUM(CASE WHEN value >= 575 AND value < 600 THEN 1 ELSE 0 END) AS \"575\",\n    SUM(CASE WHEN value >= 600 AND value < 625 THEN 1 ELSE 0 END) AS \"600\",\n    SUM(CASE WHEN value >= 625 AND value < 650 THEN 1 ELSE 0 END) AS \"625\",\n    SUM(CASE WHEN value >= 650 AND value < 675 THEN 1 ELSE 0 END) AS \"650\",\n    SUM(CASE WHEN value >= 675 AND value < 700 THEN 1 ELSE 0 END) AS \"675\",\n    SUM(CASE WHEN value >= 700 AND value < 725 THEN 1 ELSE 0 END) AS \"700\",\n    SUM(CASE WHEN value >= 725 AND value < 750 THEN 1 ELSE 0 END) AS \"725\",\n    SUM(CASE WHEN value >= 750 AND value < 775 THEN 1 ELSE 0 END) AS \"750\",\n    SUM(CASE WHEN value >= 775 AND value < 800 THEN 1 ELSE 0 END) AS \"775\",\n    SUM(CASE WHEN value >= 800 AND value < 825 THEN 1 ELSE 0 END) AS \"800\",\n    SUM(CASE WHEN value >= 825 AND value < 850 THEN 1 ELSE 0 END) AS \"825\",\n    SUM(CASE WHEN value >= 850 AND value < 875 THEN 1 ELSE 0 END) AS \"850\",\n    SUM(CASE WHEN value >= 875 AND value < 900 THEN 1 ELSE 0 END) AS \"875\",\n    SUM(CASE WHEN value >= 900 AND value < 925 THEN 1 ELSE 0 END) AS \"900\",\n    SUM(CASE WHEN value >= 925 AND value < 950 THEN 1 ELSE 0 END) AS \"925\",\n    SUM(CASE WHEN value >= 950 AND value < 975 THEN 1 ELSE 0 END) AS \"950\",\n    SUM(CASE WHEN value >= 975 AND value < 1000 THEN 1 ELSE 0 END) AS \"975\"\nFROM metrics\nWHERE $__timeFilter(time) \n    AND metric_name = 'speedreader.inference.duration'\n    AND tags->>'model' = '$model'\nGROUP BY time_bucket('5s', time)\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n      time_bucket('5s', time) AS time,\n      metric_name AS metric,\n      AVG(value) AS \"Depth\"\n  FROM metrics\n  WHERE $__timeFilter(time)\n      AND metric_name = 'speedreader.inference.queue_depth'\n      AND tags->>'model' = '$model'\n      AND time_bucket('5s', time) < time_bucket('5s', NOW())\n      AND time_bucket('5s', time) > time_bucket('5s', $__timeFrom()::timestamptz)\n  GROUP BY time_bucket('5s', time), metric_name\n  ORDER BY time;"
    }
   ]
  },
  {
   "title": "Queue Wait Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n      time_bucket('5s', time) AS time,\n      metric_name AS metric,\n      AVG(value) AS \"Duration\"\n  FROM metrics\n  WHERE $__timeFilter(time)\n      AND metric_name = 'speedreader.inference.queue_wait_duration'\n      AND tags->>'model' = '$model'\n      AND time_bucket('5s', time) < time_bucket('5s', NOW())\n      AND time_bucket('5s', time) > time_bucket('5s', $__timeFrom()::timestamptz)\n  GROUP BY time_bucket('5s', time), metric_name\n  ORDER BY time;"
    }
   ]
  }
 ]
}