{
 "title": "System",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Inference Duration (HeatMap)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(InferenceDuration_milliseconds_bucket[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inference Duration (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(InferenceDuration_milliseconds_bucket[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "Total cores used",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"speedreader-dev-app-1\"}[15s]))",
     "legendFormat": "Cores"
    },
    {
     "expr": "container_spec_cpu_quota{name=\"speedreader-dev-app-1\"}/100000",
     "legendFormat": "Max Cores"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{name=\"speedreader-dev-app-1\"}/2^30",
     "legendFormat": "Memory"
    },
    {
     "expr": "container_spec_memory_limit_bytes{name=\"speedreader-dev-app-1\"}/2^30",
     "legendFormat": "Max Memory"
    }
   ]
  }
 ]
}