name: Dynamic Build
on:
  workflow_call:
jobs:
  build:
    name: Build SpeedReader (Dynamic)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install zig
        uses: mlugg/setup-zig@v2
      - name: Install Dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'
      - name: Build Dynamically Linked Binary
        run: dotnet publish -r linux-x64 Src/Frontend -p:OnnxLinkMode=Dynamic -p:BuildOnnx=true -p:BuildSROrt=true
      - name: Smoke Test
        run: |
          Src/Frontend/bin/Release/net10.0/linux-x64/publish/speedread hello.png | grep '"text": "Hello"' || exit 1
      - name: Upload libonnxruntime.so
        uses: actions/upload-artifact@v4
        with:
          name: libonnxruntime.so
          path: Src/Native/onnx/out/shared/libonnxruntime.so
      - name: Upload Dynamically Linked Binary
        uses: actions/upload-artifact@v4
        with:
          name: speedreader-dynamic
          path: Src/Frontend/bin/Release/net10.0/linux-x64/publish/speedread
      - name: Debug Info
        if: ${{ env.ACT }} && always()
        run: uv run ./ci/get-container-id.py
